-- Durable, server-only source health records. The source governance gate
-- remains the authority for whether an endpoint may be fetched.
CREATE TABLE IF NOT EXISTS public.job_ingestion_runs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id INTEGER REFERENCES public.job_ingestion_tasks(id) ON DELETE SET NULL,
    source_id VARCHAR(100) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'running',
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at TIMESTAMPTZ,
    latency_ms INTEGER,
    fetched_count INTEGER NOT NULL DEFAULT 0,
    upserted_count INTEGER NOT NULL DEFAULT 0,
    skipped_count INTEGER NOT NULL DEFAULT 0,
    error_code VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_job_ingestion_runs_status CHECK (status IN ('running', 'succeeded', 'retry', 'failed', 'blocked')),
    CONSTRAINT ck_job_ingestion_runs_fetched CHECK (fetched_count >= 0),
    CONSTRAINT ck_job_ingestion_runs_upserted CHECK (upserted_count >= 0),
    CONSTRAINT ck_job_ingestion_runs_skipped CHECK (skipped_count >= 0),
    CONSTRAINT ck_job_ingestion_runs_latency CHECK (latency_ms IS NULL OR latency_ms >= 0)
);

CREATE INDEX IF NOT EXISTS ix_job_ingestion_runs_source_finished
    ON public.job_ingestion_runs (source_id, finished_at);

ALTER TABLE public.job_ingestion_runs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.job_ingestion_runs FROM anon, authenticated;
