-- Shared job catalogue. Automated inserts must use the approved-source server path.
CREATE TABLE IF NOT EXISTS public.job_listings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_name VARCHAR(100) NOT NULL,
    external_id VARCHAR(300) NOT NULL,
    title VARCHAR(250) NOT NULL,
    company_name VARCHAR(200) NOT NULL DEFAULT '',
    location VARCHAR(300) NOT NULL DEFAULT '',
    work_mode VARCHAR(20),
    contract_type VARCHAR(10),
    description TEXT NOT NULL DEFAULT '',
    application_url VARCHAR(1000) NOT NULL,
    salary_range VARCHAR(200) NOT NULL DEFAULT '',
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_job_listings_source_external_id UNIQUE (source_name, external_id),
    CONSTRAINT ck_job_listings_work_mode CHECK (work_mode IS NULL OR work_mode IN ('remote', 'hybrid', 'on_site')),
    CONSTRAINT ck_job_listings_contract_type CHECK (contract_type IS NULL OR contract_type IN ('CLT', 'PJ')),
    CONSTRAINT ck_job_listings_status CHECK (status IN ('active', 'expired'))
);

CREATE INDEX IF NOT EXISTS ix_job_listings_status ON public.job_listings (status);
ALTER TABLE public.job_listings ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public.job_listings TO anon, authenticated;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename = 'job_listings'
          AND policyname = 'job_listings_active_read'
    ) THEN
        CREATE POLICY job_listings_active_read
            ON public.job_listings
            FOR SELECT TO anon, authenticated
            USING (status = 'active');
    END IF;
END $$;

-- No INSERT/UPDATE/DELETE policy is granted to anon/authenticated. The API's
-- service-role path is separately gated by source_governance before each fetch.

-- Durable server-only queue. Claims use short leases so interrupted workers are
-- recoverable; idempotency prevents duplicate runs from schedulers/retries.
CREATE TABLE IF NOT EXISTS public.job_ingestion_tasks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id VARCHAR(100) NOT NULL,
    idempotency_key VARCHAR(180) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'pending',
    attempts INTEGER NOT NULL DEFAULT 0,
    available_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    locked_by VARCHAR(80),
    locked_until TIMESTAMPTZ,
    lease_token VARCHAR(64),
    last_error_code VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at TIMESTAMPTZ,
    CONSTRAINT uq_job_ingestion_tasks_idempotency UNIQUE (idempotency_key),
    CONSTRAINT ck_job_ingestion_tasks_status CHECK (status IN ('pending', 'running', 'retry', 'succeeded', 'failed')),
    CONSTRAINT ck_job_ingestion_tasks_attempts CHECK (attempts >= 0)
);

CREATE INDEX IF NOT EXISTS ix_job_ingestion_tasks_claim
    ON public.job_ingestion_tasks (status, available_at, locked_until, id);
ALTER TABLE public.job_ingestion_tasks ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.job_ingestion_tasks FROM anon, authenticated;
